dist: xenial
language: python
python:
    - 3.9
install:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
    - poetry add --dev codecov
    - poetry install
script:
    - poetry run flake8
    - poetry run mypy --install-types
